# Generated by Django 5.2.9 on 2025-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pescadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Digite um nome"),
                ),
                (
                    "email",
                    models.EmailField(max_length=200, verbose_name="Digite um email"),
                ),
            ],
        ),
    ]
