# Generated by Django 5.2.9 on 2025-12-02 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pescadores",
            name="data_cadastro",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Data de cadastro do pescador. pode ser ajustada manualmente",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pescadores",
            name="situacao_defeso",
            field=models.CharField(
                choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                default="inativo",
                help_text="Situaçao do defeso do pescador",
                max_length=20,
            ),
        ),
    ]
