# Generated by Django 5.2.9 on 2025-12-03 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_pescadores_data_cadastro_pescadores_situacao_defeso"),
    ]

    operations = [
        migrations.AddField(
            model_name="pescadores",
            name="celular",
            field=models.CharField(
                blank=True,
                help_text="Formato: (99) 99999-9999",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato válido: (99) 99999-9999",
                        regex="^\\(\\d{2}\\) \\d{4,5}-\\d{4}$",
                    )
                ],
                verbose_name="Digite o numero de celular",
            ),
        ),
    ]
