# Generated by Django 5.2.9 on 2025-12-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_pescadores_celular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pescadores",
            name="celular",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Digite um celular"
            ),
        ),
    ]
