# Generated by Django 5.2.9 on 2025-12-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_pescadores_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pescadores",
            name="cpf",
        ),
    ]
