# Generated by Django 5.2.9 on 2025-12-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_remove_pescadores_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="pescadores",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, unique=True, verbose_name="Digite o cpf"
            ),
        ),
    ]
